### ISSUE TITLE
Prevent click and scroll underneath drawer

### ISSUE THREAD

**Issue by vonwao** [stoeffel/react-motion-drawer#50] opened 2018-05-30 21:06 UTC
Clicks on the grayed-out overlay generate click events in the component behind the drawer.

You can also scroll the content behind the drawer.  (I think in most cases that's not desirable).

**Comment by kevinthecity** [comment] 2018-07-03 18:11
Also would love to see this

**Comment by Redmega** [comment] 2018-07-03 20:54
So this is fixed by #51, but introduces some hard coded styling to the body, which might interfere with the users' styling. I'm not satisfied by that approach but I'm not sure if a better alternative exists, so I may merge it regardless.

**Comment by Redmega** [comment] 2018-07-03 20:56
also just realized this is a duplicate of #24, so closing and moving conversation there.

**Closed by Redmega** 2018-07-03 20:56 UTC
Labels: duplicate
